-- Insert default categories
INSERT INTO categories (name, description, created_at) VALUES
                                                           ('Politique', 'Actualités politiques nationales et internationales', NOW()),
                                                           ('Économie', 'Actualités économiques et financières', NOW()),
                                                           ('Sport', 'Actualités sportives', NOW()),
                                                           ('Culture', 'Actualités culturelles et artistiques', NOW()),
                                                           ('Technologie', 'Actualités technologiques et innovations', NOW()),
                                                           ('Santé', 'Actualités santé et bien-être', NOW());

-- Insert default admin user (password: admin123)
INSERT INTO users (username, password, email, first_name, last_name, role, created_at, updated_at, active) VALUES
    ('admin', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'admin@newsplatform.com', 'Admin', 'User', 'ADMIN', NOW(), NOW(), true);

-- Insert default editor user (password: editor123)
INSERT INTO users (username, password, email, first_name, last_name, role, created_at, updated_at, active) VALUES
    ('editor', '$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a', 'editor@newsplatform.com', 'Editor', 'User', 'EDITOR', NOW(), NOW(), true);

-- Insert sample articles
INSERT INTO articles (title, summary, content, category_id, author_id, created_at, updated_at, published_at, published, view_count) VALUES
                                                                                                                                        ('Nouvelle réforme du système de santé annoncée',
                                                                                                                                         'Le gouvernement dévoile un plan ambitieux pour moderniser le système de santé national avec un investissement de 5 milliards d\'euros.',
                                                                                                                                         '<p>Le ministre de la Santé a présenté aujourd\'hui les grandes lignes d\'une réforme majeure du système de santé qui devrait être mise en œuvre progressivement sur les cinq prochaines années.</p><p>Cette réforme prévoit notamment :</p><ul><li>La création de 100 nouveaux centres de santé de proximité</li><li>Le recrutement de 10 000 professionnels de santé supplémentaires</li><li>La modernisation des équipements hospitaliers</li><li>Le développement de la télémédecine</li></ul><p>L\'objectif est de réduire les déserts médicaux et d\'améliorer l\'accès aux soins pour tous les citoyens, particulièrement dans les zones rurales.</p>',
                                                                                                                                         6, 2, NOW(), NOW(), NOW(), true, 150),

                                                                                                                                        ('Les marchés financiers en hausse après les annonces de la BCE',
                                                                                                                                         'La Banque Centrale Européenne maintient ses taux directeurs, rassurant les investisseurs sur la stabilité économique.',
                                                                                                                                         '<p>Les principales places boursières européennes ont clôturé en hausse ce vendredi, portées par les déclarations rassurantes de la présidente de la BCE.</p><p>Le CAC 40 a gagné 1,2%, tandis que le DAX allemand progressait de 1,5%. Cette hausse s\'explique par plusieurs facteurs :</p><ul><li>Le maintien des taux directeurs à leur niveau actuel</li><li>Les prévisions optimistes pour la croissance en zone euro</li><li>La stabilisation de l\'inflation autour de 2%</li></ul><p>Les analystes restent toutefois prudents et surveillent l\'évolution de la situation géopolitique internationale.</p>',
                                                                                                                                         2, 2, NOW(), NOW(), NOW(), true, 230),

                                                                                                                                        ('Victoire éclatante de l\'équipe nationale en finale',
                                                                                                                                         'L\'équipe nationale remporte le championnat après une finale haletante face à l\'Espagne (3-2).',
                                                                                                                                         '<p>Quelle soirée mémorable pour les supporters ! L\'équipe nationale a décroché le titre de champion après un match épique contre l\'Espagne.</p><p>Les moments forts du match :</p><ul><li>Ouverture du score à la 15e minute par notre attaquant vedette</li><li>Égalisation espagnole juste avant la mi-temps</li><li>Deux buts en seconde période pour mener 3-1</li><li>Réduction du score espagnole à la 85e minute</li><li>Dernières minutes sous haute tension</li></ul><p>Cette victoire marque le retour au sommet de notre équipe nationale après 10 ans d\'attente. Les célébrations se poursuivent dans tout le pays.</p>',
                                                                                                                                         3, 2, NOW(), NOW(), NOW(), true, 450),

                                                                                                                                        ('Intelligence Artificielle : les dernières avancées révolutionnaires',
                                                                                                                                         'Les géants de la tech dévoilent leurs nouvelles innovations en IA qui promettent de transformer notre quotidien.',
                                                                                                                                         '<p>Le secteur de l\'intelligence artificielle connaît une accélération sans précédent avec l\'annonce de plusieurs breakthrough technologiques majeurs cette semaine.</p><p>Les principales innovations présentées :</p><ul><li>Un nouveau modèle de langage capable de comprendre et générer du code dans 50 langages de programmation</li><li>Une IA médicale détectant les cancers avec 99% de précision</li><li>Des assistants virtuels ultra-réalistes pour l\'éducation</li><li>Des systèmes de traduction instantanée en temps réel</li></ul><p>Ces avancées soulèvent également des questions éthiques importantes sur l\'impact de l\'IA sur l\'emploi et la vie privée.</p>',
                                                                                                                                         5, 2, NOW(), NOW(), NOW(), true, 380),

                                                                                                                                        ('Festival international du cinéma : le palmarès complet',
                                                                                                                                         'Le film français "Les Oubliés" remporte la Palme d\'Or lors de la 78e édition du festival.',
                                                                                                                                         '<p>La cérémonie de clôture du Festival international du cinéma s\'est tenue hier soir, couronnant les meilleures œuvres de cette édition exceptionnelle.</p><p>Le palmarès complet :</p><ul><li>Palme d\'Or : "Les Oubliés" de Marie Dubois (France)</li><li>Grand Prix : "Silent Echo" de Kim Jong-un (Corée du Sud)</li><li>Prix de la mise en scène : Roberto Martinez (Espagne)</li><li>Prix d\'interprétation féminine : Sarah Johnson (États-Unis)</li><li>Prix d\'interprétation masculine : Pierre Durand (France)</li></ul><p>Cette édition a été marquée par une forte présence du cinéma européen et asiatique, avec des œuvres engagées abordant les grands enjeux contemporains.</p>',
                                                                                                                                         4, 2, NOW(), NOW(), NOW(), true, 290),

                                                                                                                                        ('Tensions diplomatiques : sommet d\'urgence convoqué',
                                                                                                                                         'Les dirigeants européens se réunissent à Bruxelles pour discuter de la crise diplomatique actuelle.',
                                                                                                                                         '<p>Face à l\'escalade des tensions internationales, un sommet extraordinaire a été convoqué d\'urgence à Bruxelles pour trouver une solution diplomatique.</p><p>Les points clés à l\'ordre du jour :</p><ul><li>Médiation dans le conflit commercial en cours</li><li>Renforcement de la coopération en matière de sécurité</li><li>Nouvelles sanctions économiques potentielles</li><li>Plan d\'aide humanitaire d\'urgence</li></ul><p>Les observateurs internationaux suivent de près ces négociations qui pourraient avoir des répercussions majeures sur l\'équilibre géopolitique mondial.</p>',
                                                                                                                                         1, 2, NOW(), NOW(), NOW(), true, 520),

                                                                                                                                        ('Découverte scientifique : un nouveau traitement contre Alzheimer',
                                                                                                                                         'Des chercheurs annoncent des résultats prometteurs pour un médicament révolutionnaire contre la maladie d\'Alzheimer.',
                                                                                                                                         '<p>Une équipe de chercheurs internationale vient de publier les résultats d\'une étude clinique de phase 3 montrant l\'efficacité d\'un nouveau traitement contre la maladie d\'Alzheimer.</p><p>Les résultats de l\'étude :</p><ul><li>Ralentissement de 60% de la progression de la maladie</li><li>Amélioration des fonctions cognitives chez 75% des patients</li><li>Effets secondaires minimes observés</li><li>Traitement par voie orale, facilitant l\'administration</li></ul><p>Cette découverte représente un espoir immense pour les millions de personnes touchées par cette maladie neurodégénérative.</p>',
                                                                                                                                         6, 2, NOW(), NOW(), NOW(), true, 680),

                                                                                                                                        ('Crise économique : le gouvernement annonce un plan de relance',
                                                                                                                                         'Un package de 50 milliards d\'euros pour soutenir l\'économie et préserver l\'emploi.',
                                                                                                                                         '<p>Face aux difficultés économiques actuelles, le gouvernement a dévoilé un plan de relance massif visant à soutenir les entreprises et maintenir l\'emploi.</p><p>Les mesures principales du plan :</p><ul><li>Aides directes aux PME et TPE : 20 milliards</li><li>Investissements dans la transition écologique : 15 milliards</li><li>Formation et reconversion professionnelle : 10 milliards</li><li>Soutien aux secteurs les plus touchés : 5 milliards</li></ul><p>Ce plan devrait permettre de sauvegarder 500 000 emplois et de relancer la croissance dès le prochain trimestre selon les prévisions gouvernementales.</p>',
                                                                                                                                         2, 2, NOW(), NOW(), NOW(), true, 420),

                                                                                                                                        ('Jeux Olympiques : début des compétitions dans 100 jours',
                                                                                                                                         'Les préparatifs s\'intensifient pour accueillir les athlètes du monde entier cet été.',
                                                                                                                                         '<p>À exactement 100 jours de la cérémonie d\'ouverture, les organisateurs des Jeux Olympiques ont fait le point sur l\'avancement des préparatifs.</p><p>État des lieux :</p><ul><li>95% des infrastructures sportives sont achevées</li><li>Le village olympique peut accueillir 15 000 athlètes</li><li>2 millions de billets déjà vendus</li><li>20 000 volontaires mobilisés</li></ul><p>Les autorités promettent des Jeux spectaculaires et écoresponsables, avec une empreinte carbone réduite de 50% par rapport aux éditions précédentes.</p>',
                                                                                                                                         3, 2, NOW(), NOW(), NOW(), true, 350),

                                                                                                                                        ('Révolution numérique : le métavers transforme le monde du travail',
                                                                                                                                         'De plus en plus d\'entreprises adoptent les espaces virtuels pour le télétravail et les réunions.',
                                                                                                                                         '<p>Le métavers n\'est plus une simple tendance futuriste : il devient une réalité concrète pour des milliers d\'entreprises qui repensent leur organisation du travail.</p><p>Les innovations observées :</p><ul><li>Bureaux virtuels immersifs en 3D</li><li>Réunions holographiques ultra-réalistes</li><li>Formations professionnelles en réalité virtuelle</li><li>Espaces de coworking dans le métavers</li></ul><p>Cette transformation pose néanmoins des défis en termes d\'équipement, de formation et de bien-être des employés qui doivent s\'adapter à ces nouveaux environnements de travail.</p>',
                                                                                                                                         5, 2, NOW(), NOW(), NOW(), true, 295),

                                                                                                                                        ('Exposition exceptionnelle : les chefs-d\'œuvre de la Renaissance',
                                                                                                                                         'Le musée national accueille 150 œuvres majeures prêtées par les plus grands musées du monde.',
                                                                                                                                         '<p>Une exposition événement s\'ouvre demain au musée national, rassemblant pour la première fois des chefs-d\'œuvre de la Renaissance italienne habituellement dispersés dans le monde entier.</p><p>Les œuvres phares de l\'exposition :</p><ul><li>Trois tableaux inédits de Léonard de Vinci</li><li>Une sculpture monumentale de Michel-Ange</li><li>Des fresques restaurées de Raphaël</li><li>Une collection exceptionnelle de dessins préparatoires</li></ul><p>L\'exposition, qui durera six mois, s\'accompagne d\'un programme pédagogique ambitieux avec des conférences, ateliers et visites guidées pour tous les publics.</p>',
                                                                                                                                         4, 2, NOW(), NOW(), NOW(), true, 410),

                                                                                                                                        ('Réforme de l\'éducation : ce qui va changer à la rentrée',
                                                                                                                                         'Le ministère dévoile les grandes lignes de la nouvelle réforme qui concernera tous les niveaux scolaires.',
                                                                                                                                         '<p>La ministre de l\'Éducation a présenté aujourd\'hui les principales mesures de la réforme qui entrera en vigueur dès la prochaine rentrée scolaire.</p><p>Les changements majeurs :</p><ul><li>Classes limitées à 20 élèves en primaire</li><li>Introduction de l\'informatique dès le CP</li><li>Renforcement de l\'apprentissage des langues étrangères</li><li>Nouveau système d\'évaluation plus personnalisé</li></ul><p>Cette réforme, fruit de deux ans de concertation avec les enseignants et les parents d\'élèves, vise à moderniser le système éducatif et réduire les inégalités scolaires.</p>',
                                                                                                                                         1, 2, NOW(), NOW(), NOW(), true, 340);